name: cpanminus

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:

  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::cpanminus
          verbose: true
      - run: |
          ls -Rl $HOME/perl5
          whoami
          cpanm --version

  cached-cpanm-with-others:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: Acme
          verbose: true
      - run: |
          cpanm --version
          perl -MAcme -E 'say "ok"'
